# -*- coding: utf-8 -*-
"""algorithms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m4nyIThMAPgdzuW9Y618V0lIxesEx6H3

##PREPROCESSING
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

dftrain = pd.read_csv('/content/MNIST_train.csv')
dfval = pd.read_csv('/content/MNIST_validation.csv')

dftrain.drop('even',axis=1,inplace=True)
dfval.drop('even',axis=1,inplace=True)

dftrain

import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def read_data_multiclass(trainfile='MNIST_train.csv', validationfile='MNIST_validation.csv'):

    dftrain = pd.read_csv(trainfile)
    dfval = pd.read_csv(validationfile)
    featurecols = [col for col in dftrain.columns if col not in ['label', 'even']]
    targetcol = 'label'

    Xtrain = dftrain[featurecols]
    ytrain = dftrain[targetcol]

    Xval = dfval[featurecols]
    yval = dfval[targetcol]

    return (Xtrain, ytrain, Xval, yval)

Xtrain, ytrain, Xval, yval = read_data_multiclass('MNIST_train.csv', 'MNIST_validation.csv')

"""##SIMPLE XGBOOST"""

class XGBTree:
    def __init__(self, max_depth, delta, gamma, max_thresholds=50):
        self.max_depth = max_depth
        self.delta = delta
        self.gamma = gamma
        self.max_thresholds = max_thresholds
        self.feature_index = None
        self.threshold = None
        self.left_child = None
        self.right_child = None
        self.value = None
        self.gain = -float('inf')

    def fit(self, X, y, grad, hess, feature_indices, current_depth):
        if current_depth == self.max_depth or X.shape[0] <= 1:
            self._set_leaf_value(grad, hess)
            return

        best_gain = -float('inf')
        best_feature_index = None
        best_threshold = None
        Grad_total = np.sum(grad)
        Hess_total = np.sum(hess)

        for feature_index in feature_indices:
            thresholds = np.unique(X[:, feature_index])
            if len(thresholds) > self.max_thresholds:
                q = np.linspace(0.01, 0.99, self.max_thresholds)
                thresholds = np.unique(np.quantile(X[:, feature_index], q))

            for threshold in thresholds:
                left_mask = X[:, feature_index] <= threshold
                right_mask = ~left_mask
                if np.sum(left_mask) < 1 or np.sum(right_mask) < 1:
                    continue

                L_Grad_total = np.sum(grad[left_mask])
                L_Hess_total = np.sum(hess[left_mask])
                R_Grad_total = np.sum(grad[right_mask])
                R_Hess_total = np.sum(hess[right_mask])

                gain = 0.5 * (
                    (L_Grad_total ** 2) / (L_Hess_total + self.delta) +
                    (R_Grad_total ** 2) / (R_Hess_total + self.delta) -
                    (Grad_total ** 2) / (Hess_total + self.delta)
                )

                if gain > best_gain:
                    best_gain = gain
                    best_feature_index = feature_index
                    best_threshold = threshold

        self.gain = best_gain

        if best_gain <= self.gamma:
            self._set_leaf_value(grad, hess)
            return

        self.feature_index = best_feature_index
        self.threshold = best_threshold
        left_mask = X[:, self.feature_index] <= self.threshold
        right_mask = ~left_mask

        self.left_child = XGBTree(self.max_depth, self.delta, self.gamma)
        self.right_child = XGBTree(self.max_depth, self.delta, self.gamma)

        self.left_child.fit(
            X[left_mask], y[left_mask], grad[left_mask], hess[left_mask],
            feature_indices, current_depth + 1
        )
        self.right_child.fit(
            X[right_mask], y[right_mask], grad[right_mask], hess[right_mask],
            feature_indices, current_depth + 1
        )

    def _set_leaf_value(self, grad, hess):
        Grad_total = np.sum(grad)
        Hess_total = np.sum(hess)
        self.value = -Grad_total / (Hess_total + self.delta)

    def predict(self, X):
        if self.value is not None:
            return np.full(X.shape[0], self.value)

        feature = X[:, self.feature_index]
        left_mask = feature <= self.threshold
        right_mask = ~left_mask
        predictions = np.zeros(X.shape[0])

        if np.sum(left_mask) > 0:
            predictions[left_mask] = self.left_child.predict(X[left_mask])
        if np.sum(right_mask) > 0:
            predictions[right_mask] = self.right_child.predict(X[right_mask])
        return predictions

class XGBMultiClassClassifier:
    def __init__(self, n_estimators=100, learning_rate=0.3, delta=1.0, gamma=0,
                 max_depth=6, colsample_bytree=0.1, subsample=0.8):
        self.n_estimators = n_estimators
        self.learning_rate = learning_rate
        self.delta = delta
        self.gamma = gamma
        self.max_depth = max_depth
        self.colsample_bytree = colsample_bytree
        self.subsample = subsample
        self.classifiers = []
        self.n_classes = None

    def softmax(self, x):
        exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
        return exp_x / np.sum(exp_x, axis=1, keepdims=True)

    def fit(self, X, y):
        self.n_classes = len(np.unique(y))
        self.classifiers = []


        for class_idx in range(self.n_classes):

            y_binary = (y == class_idx).astype(int)

            y_mean = np.mean(y_binary)
            init_pred = np.log(y_mean / (1 - y_mean)) if y_mean not in [0, 1] else 0
            pred = np.full_like(y_binary, fill_value=init_pred, dtype=float)

            n_features_total = X.shape[1]
            X_np = X.values if hasattr(X, 'values') else X

            if self.subsample < 1.0:
                n_samples = int(X.shape[0] * self.subsample)
                sample_indices = np.random.choice(X.shape[0], n_samples, replace=False)
            else:
                sample_indices = np.arange(X.shape[0])

            trees = []

            for i in range(self.n_estimators):
                prob = 1 / (1 + np.exp(-pred[sample_indices]))
                grad = prob - y_binary[sample_indices]
                hess = prob * (1 - prob)
                hess = np.maximum(hess, 1e-6)

                n_features_subsample = int(n_features_total * self.colsample_bytree)
                feature_indices = np.random.choice(
                    n_features_total, size=n_features_subsample, replace=False
                )

                tree = XGBTree(
                    max_depth=self.max_depth,
                    delta=self.delta,
                    gamma=self.gamma
                )
                tree.fit(X_np[sample_indices], y_binary[sample_indices],
                        grad, hess, feature_indices, current_depth=0)

                if tree.gain <= self.gamma and i > 10:
                    break

                update = tree.predict(X_np[sample_indices])
                pred[sample_indices] += self.learning_rate * update
                trees.append(tree)

                if i % 20 == 0:
                    current_prob = 1 / (1 + np.exp(-pred[sample_indices]))
                    current_acc = np.mean((current_prob > 0.5) == y_binary[sample_indices])

            self.classifiers.append({
                'trees': trees,
                'init_pred': init_pred
            })



    def predict_proba(self, X):

        X_np = X.values if hasattr(X, 'values') else X
        n_samples = X.shape[0]


        raw_scores = np.zeros((n_samples, self.n_classes))

        for class_idx in range(self.n_classes):
            classifier = self.classifiers[class_idx]
            pred = np.full(n_samples, classifier['init_pred'])

            for tree in classifier['trees']:
                pred += self.learning_rate * tree.predict(X_np)

            raw_scores[:, class_idx] = pred


        return self.softmax(raw_scores)

    def predict(self, X):

        proba = self.predict_proba(X)
        return np.argmax(proba, axis=1)

Xtrain, ytrain, Xval, yval = read_data_multiclass('MNIST_train.csv', 'MNIST_validation.csv')

"""doesnt do much better,acuracy around 0.89 with 5 trees,depth=6,0.1colsample,lr=0.3 . training takes nearly 5-6 minutes

###XGBOOST (TRAIN ON VAL AND TEST ON TRAIN)

##PCA WITH KNN
"""

from collections import Counter
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

class PCA:


    def __init__(self, n_components):
        self.n_components = n_components
        self.components = None
        self.mean = None
        self.explained_variance_ratio = None

    def fit(self, X):

        self.mean = np.mean(X, axis=0)
        X_centered = X - self.mean


        cov_matrix = np.cov(X_centered, rowvar=False)


        eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)


        sorted_indices = np.argsort(eigenvalues)[::-1]
        eigenvalues = eigenvalues[sorted_indices]
        eigenvectors = eigenvectors[:, sorted_indices]


        self.components = eigenvectors[:, :self.n_components]

        total_variance = np.sum(eigenvalues)
        self.explained_variance_ratio = eigenvalues[:self.n_components] / total_variance

        return self

    def transform(self, X):
        X_centered = X - self.mean
        return np.dot(X_centered, self.components)

    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)
class KNN:


    def __init__(self, k=5, distance_metric='euclidean', weights='uniform'):
        self.k = k
        self.distance_metric = distance_metric
        self.weights = weights
        self.X_train = None
        self.y_train = None

    def _calculate_distance(self, x1, x2):

        if self.distance_metric == 'euclidean':
            return np.sqrt(np.sum((x1 - x2) ** 2))
        elif self.distance_metric == 'manhattan':
            return np.sum(np.abs(x1 - x2))
        elif self.distance_metric == 'cosine':
            dot_product = np.dot(x1, x2)
            norm_x1 = np.linalg.norm(x1)
            norm_x2 = np.linalg.norm(x2)
            return 1 - (dot_product / (norm_x1 * norm_x2))


    def fit(self, X, y):

        self.X_train = X
        self.y_train = y
        return self

    def predict_single(self, x):

        distances = []

        for i, x_train in enumerate(self.X_train):
            dist = self._calculate_distance(x, x_train)
            distances.append((dist, self.y_train[i]))


        distances.sort(key=lambda x: x[0])
        k_nearest = distances[:self.k]


        labels = [label for _, label in k_nearest]
        dists = [dist for dist, _ in k_nearest]


        if self.weights == 'distance':

            weights = [1 / (d + 1e-8) for d in dists]
            weight_dict = {}
            for label, weight in zip(labels, weights):
                if label in weight_dict:
                    weight_dict[label] += weight
                else:
                    weight_dict[label] = weight


            return max(weight_dict.items(), key=lambda x: x[1])[0]

        else:

            return Counter(labels).most_common(1)[0][0]

    def predict(self, X):

        return np.array([self.predict_single(x) for x in X])

    def predict_proba(self, X):

        probabilities = []

        for x in X:
            distances = []


            for i, x_train in enumerate(self.X_train):
                dist = self._calculate_distance(x, x_train)
                distances.append((dist, self.y_train[i]))


            distances.sort(key=lambda x: x[0])
            k_nearest = distances[:self.k]

            labels = [label for _, label in k_nearest]


            label_counts = Counter(labels)
            prob = np.zeros(10)

            for label, count in label_counts.items():
                prob[label] = count / self.k

            probabilities.append(prob)

        return np.array(probabilities)
class Simple_PCA_KNN:


    def __init__(self, n_components=100, k=5):
        self.n_components = n_components
        self.k = k
        self.pca = None
        self.knn = None

    def fit(self, X, y):
        self.pca = PCA(self.n_components)
        X_pca = self.pca.fit_transform(X)

        self.knn = KNN(k=self.k, distance_metric='euclidean', weights='distance')
        self.knn.fit(X_pca, y)
        return self

    def predict(self, X):
        X_pca = self.pca.transform(X)
        return self.knn.predict(X_pca)

    def predict_proba(self, X):
        X_pca = self.pca.transform(X)
        return self.knn.predict_proba(X_pca)

"""#Ensemble with KNN and SVM"""

import numpy as np
from collections import Counter

class SVM:
    def __init__(self, learning_rate=0.001, lambda_param=0.01, n_iterations=1000):
        self.learning_rate = learning_rate
        self.lambda_param = lambda_param
        self.n_iterations = n_iterations
        self.classifiers = []
        self.classes = None

    def _train_binary(self, X, y):

        n_samples, n_features = X.shape
        w = np.zeros(n_features)
        b = 0


        y_ = np.where(y <= 0, -1, 1)

        for _ in range(self.n_iterations):
            for idx, x_i in enumerate(X):
                condition = y_[idx] * (np.dot(x_i, w) - b) >= 1

                if condition:
                    w -= self.learning_rate * (2 * self.lambda_param * w)
                else:
                    w -= self.learning_rate * (2 * self.lambda_param * w - np.dot(x_i, y_[idx]))
                    b -= self.learning_rate * y_[idx]

        return w, b

    def fit(self, X, y):
        self.classes = np.unique(y)


        for c in self.classes:

            y_binary = np.where(y == c, 1, -1)
            w, b = self._train_binary(X, y_binary)
            self.classifiers.append((w, b))

        return self

    def _decision_function(self, X):

        scores = []
        for w, b in self.classifiers:
            score = np.dot(X, w) - b
            scores.append(score)
        return np.array(scores).T

    def predict(self, X):
        scores = self._decision_function(X)
        return self.classes[np.argmax(scores, axis=1)]

    def predict_proba(self, X):

        scores = self._decision_function(X)

        exp_scores = np.exp(scores - np.max(scores, axis=1, keepdims=True))
        probas = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)
        return probas





class SVM_KNN_Ensemble:


    def __init__(self, use_pca=True, n_components=100, voting='soft'):

        self.use_pca = use_pca
        self.n_components = n_components
        self.voting = voting
        self.pca = None
        self.models = []
        self.model_names = []

    def fit(self, X, y):

        if self.use_pca:

            self.pca = PCA(self.n_components)
            X_transformed = self.pca.fit_transform(X)

        else:
            X_transformed = X





        svm = SVM(learning_rate=0.001, lambda_param=0.01, n_iterations=10)
        svm.fit(X_transformed, y)
        self.models.append(svm)
        self.model_names.append("SVM")



        knn1 = KNN(k=3, distance_metric='euclidean', weights='distance')
        knn1.fit(X_transformed, y)
        self.models.append(knn1)
        self.model_names.append("KNN-k3-euclidean")


        return self

    def predict(self, X):

        if self.use_pca:
            X_transformed = self.pca.transform(X)
        else:
            X_transformed = X

        if self.voting == 'hard':

            all_predictions = []
            for model in self.models:
                pred = model.predict(X_transformed)
                all_predictions.append(pred)

            all_predictions = np.array(all_predictions)
            final_predictions = []

            for i in range(X.shape[0]):
                votes = all_predictions[:, i]
                final_predictions.append(Counter(votes).most_common(1)[0][0])

            return np.array(final_predictions)

        else:

            all_probas = []
            for model in self.models:
                if hasattr(model, 'predict_proba'):
                    proba = model.predict_proba(X_transformed)
                else:

                    pred = model.predict(X_transformed)
                    proba = np.zeros((len(pred), 10))
                    proba[np.arange(len(pred)), pred.astype(int)] = 1

                all_probas.append(proba)


            avg_proba = np.mean(all_probas, axis=0)
            return np.argmax(avg_proba, axis=1)

    def predict_proba(self, X):

        if self.use_pca:
            X_transformed = self.pca.transform(X)
        else:
            X_transformed = X

        all_probas = []
        for model in self.models:
            if hasattr(model, 'predict_proba'):
                proba = model.predict_proba(X_transformed)
            else:
                pred = model.predict(X_transformed)
                proba = np.zeros((len(pred), 10))
                proba[np.arange(len(pred)), pred.astype(int)] = 1

            all_probas.append(proba)

        return np.mean(all_probas, axis=0)

    def evaluate_individual_models(self, X, y):

        if self.use_pca:
            X_transformed = self.pca.transform(X)
        else:
            X_transformed = X



        from sklearn.metrics import accuracy_score

        for model, name in zip(self.models, self.model_names):
            pred = model.predict(X_transformed)
            acc = accuracy_score(y, pred)
            print(f"{name:25s}: {acc*100:.2f}%")

"""## SVM + KNN + Logistic"""

import numpy as np
from collections import Counter

class SVM:


    def __init__(self, learning_rate=0.001, lambda_param=0.01, n_iterations=1000):
        self.learning_rate = learning_rate
        self.lambda_param = lambda_param
        self.n_iterations = n_iterations
        self.classifiers = []
        self.classes = None

    def _train_binary(self, X, y):

        n_samples, n_features = X.shape
        w = np.zeros(n_features)
        b = 0


        y_ = np.where(y <= 0, -1, 1)

        for _ in range(self.n_iterations):
            for idx, x_i in enumerate(X):
                condition = y_[idx] * (np.dot(x_i, w) - b) >= 1

                if condition:
                    w -= self.learning_rate * (2 * self.lambda_param * w)
                else:
                    w -= self.learning_rate * (2 * self.lambda_param * w - np.dot(x_i, y_[idx]))
                    b -= self.learning_rate * y_[idx]

        return w, b

    def fit(self, X, y):
        self.classes = np.unique(y)


        for c in self.classes:

            y_binary = np.where(y == c, 1, -1)
            w, b = self._train_binary(X, y_binary)
            self.classifiers.append((w, b))

        return self

    def _decision_function(self, X):

        scores = []
        for w, b in self.classifiers:
            score = np.dot(X, w) - b
            scores.append(score)
        return np.array(scores).T

    def predict(self, X):
        scores = self._decision_function(X)
        return self.classes[np.argmax(scores, axis=1)]

    def predict_proba(self, X):

        scores = self._decision_function(X)

        exp_scores = np.exp(scores - np.max(scores, axis=1, keepdims=True))
        probas = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)
        return probas

class Specialized4vs9Classifier:


    def __init__(self, k=3, distance_metric='cosine', weights='distance'):
        self.k = k
        self.distance_metric = distance_metric
        self.weights = weights
        self.X_train = None
        self.y_train = None

    def _calculate_distance(self, x1, x2):
        if self.distance_metric == 'euclidean':
            return np.sqrt(np.sum((x1 - x2) ** 2))
        elif self.distance_metric == 'manhattan':
            return np.sum(np.abs(x1 - x2))
        elif self.distance_metric == 'cosine':
            dot_product = np.dot(x1, x2)
            norm_x1 = np.linalg.norm(x1)
            norm_x2 = np.linalg.norm(x2)
            return 1 - dot_product / (norm_x1 * norm_x2 + 1e-8)


    def fit(self, X, y):


        mask = np.isin(y, [4, 9])
        if np.sum(mask) == 0:
            raise ValueError("No samples of digits 4 or 9 found in training data")

        self.X_train = X[mask]
        self.y_train = y[mask]
        return self

    def predict(self, X):
        predictions = []
        for x in X:

            distances = [self._calculate_distance(x, x_train) for x_train in self.X_train]


            k_indices = np.argsort(distances)[:self.k]
            k_nearest_labels = [self.y_train[i] for i in k_indices]
            k_distances = [distances[i] for i in k_indices]


            if self.weights == 'distance':
                weights = [1 / (d + 1e-8) for d in k_distances]
                weight_dict = {}
                for label, weight in zip(k_nearest_labels, weights):
                    if label in weight_dict:
                        weight_dict[label] += weight
                    else:
                        weight_dict[label] = weight
                prediction = max(weight_dict.items(), key=lambda x: x[1])[0]
            else:  # uniform weights
                prediction = Counter(k_nearest_labels).most_common(1)[0][0]

            predictions.append(prediction)

        return np.array(predictions)

class SVM_KNN_Logistic49Ensemble:


    def __init__(self, use_pca=True, n_components=100, voting='soft'):

        self.use_pca = use_pca
        self.n_components = n_components
        self.voting = voting
        self.pca = None
        self.models = []
        self.model_names = []
        self.specialized_4_9_classifier = None

    def fit(self, X, y):

        if self.use_pca:
            print(f"Applying PCA (n_components={self.n_components})...")
            self.pca = PCA(self.n_components)
            X_transformed_train = self.pca.fit_transform(X)
            print(f"Explained variance ratio: {np.sum(self.pca.explained_variance_ratio):.4f}")
        else:
            X_transformed_train = X



        svm = SVM(learning_rate=0.001, lambda_param=0.01, n_iterations=10)
        svm.fit(X_transformed_train, y)
        self.models.append(svm)
        self.model_names.append("SVM")


        knn1 = KNN(k=3, distance_metric='euclidean', weights='distance')
        knn1.fit(X_transformed_train, y)
        self.models.append(knn1)
        self.model_names.append("KNN-k3-euclidean")


        self.specialized_4_9_classifier = Specialized4vs9Classifier(k=1, distance_metric='cosine')
        self.specialized_4_9_classifier.fit(X_transformed_train, y)

        if self.use_pca:
            Xval_transformed = self.pca.transform(Xval_np)
        else:
            Xval_transformed = Xval_np

        mask_4_9_val = np.isin(yval_np, [4, 9])
        X_4_9_val_filtered = Xval_transformed[mask_4_9_val]
        y_4_9_val_filtered = yval_np[mask_4_9_val]



        return self

    def predict(self, X):

        if self.use_pca:
            X_transformed = self.pca.transform(X)
        else:
            X_transformed = X

        if self.voting == 'hard':

            all_predictions = []
            for model in self.models:
                pred = model.predict(X_transformed)
                all_predictions.append(pred)

            all_predictions = np.array(all_predictions)
            final_predictions = []

            for i in range(X.shape[0]):
                votes = all_predictions[:, i]
                final_predictions.append(Counter(votes).most_common(1)[0][0])


            final_predictions = self._apply_two_stage_classification(X_transformed, final_predictions)
            return np.array(final_predictions)

        else:

            all_probas = []
            for model in self.models:
                if hasattr(model, 'predict_proba'):
                    proba = model.predict_proba(X_transformed)
                else:

                    pred = model.predict(X_transformed)
                    proba = np.zeros((len(pred), 10))
                    proba[np.arange(len(pred)), pred.astype(int)] = 1

                all_probas.append(proba)


            avg_proba = np.mean(all_probas, axis=0)
            base_predictions = np.argmax(avg_proba, axis=1)

            final_predictions = self._apply_two_stage_classification(X_transformed, base_predictions)
            return final_predictions

    def _apply_two_stage_classification(self, X, base_predictions):

        final_predictions = base_predictions.copy()

        for i in range(len(X)):
            if base_predictions[i] in [4, 9]:

                specialized_pred = self.specialized_4_9_classifier.predict([X[i]])[0]
                final_predictions[i] = specialized_pred

        return final_predictions

    def predict_proba(self, X):

        if self.use_pca:
            X_transformed = self.pca.transform(X)
        else:
            X_transformed = X

        all_probas = []
        for model in self.models:
            if hasattr(model, 'predict_proba'):
                proba = model.predict_proba(X_transformed)
            else:
                pred = model.predict(X_transformed)
                proba = np.zeros((len(pred), 10))
                proba[np.arange(len(pred)), pred.astype(int)] = 1

            all_probas.append(proba)

        return np.mean(all_probas, axis=0)

    def evaluate_individual_models(self, X, y):

        if self.use_pca:
            X_transformed = self.pca.transform(X)
        else:
            X_transformed = X



        from sklearn.metrics import accuracy_score

        for model, name in zip(self.models, self.model_names):
            pred = model.predict(X_transformed)
            acc = accuracy_score(y, pred)
            print(f"{name:25s}: {acc*100:.2f}%")

"""# SVM+KNN+Logistic4&9and5&8"""

class LogisticRegression4vs9:
    def __init__(self, learning_rate=0.01, n_iterations=1000):
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.weights = None
        self.bias = None

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-np.clip(z, -250, 250)))

    def fit(self, X, y):

        y_binary = (y == 9).astype(int)

        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0


        for _ in range(self.n_iterations):
            linear_model = np.dot(X, self.weights) + self.bias
            predictions = self.sigmoid(linear_model)


            dw = (1 / n_samples) * np.dot(X.T, (predictions - y_binary))
            db = (1 / n_samples) * np.sum(predictions - y_binary)

            self.weights -= self.learning_rate * dw
            self.bias -= self.learning_rate * db

    def predict_proba(self, X):
        linear_model = np.dot(X, self.weights) + self.bias
        return self.sigmoid(linear_model)

    def predict(self, X):
        proba = self.predict_proba(X)
        return np.where(proba > 0.5, 9, 4)

class LogisticRegression5vs8:
    def __init__(self, learning_rate=0.01, n_iterations=1000):
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.weights = None
        self.bias = None

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-np.clip(z, -250, 250)))

    def fit(self, X, y):

        y_binary = (y == 8).astype(int)

        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        for _ in range(self.n_iterations):
            linear_model = np.dot(X, self.weights) + self.bias
            predictions = self.sigmoid(linear_model)

            dw = (1 / n_samples) * np.dot(X.T, (predictions - y_binary))
            db = (1 / n_samples) * np.sum(predictions - y_binary)

            self.weights -= self.learning_rate * dw
            self.bias -= self.learning_rate * db

    def predict_proba(self, X):
        linear_model = np.dot(X, self.weights) + self.bias
        return self.sigmoid(linear_model)

    def predict(self, X):
        proba = self.predict_proba(X)
        return np.where(proba > 0.5, 8, 5)

class EnhancedSVM_KNN_Ensemble:
    def __init__(self, use_pca=True, n_components=100, voting='soft'):
        self.use_pca = use_pca
        self.n_components = n_components
        self.voting = voting
        self.pca = None
        self.models = []
        self.model_names = []
        self.specialized_4_9_classifier = None
        self.specialized_5_8_classifier = None

    def fit(self, X, y):
        if self.use_pca:

            self.pca = PCA(self.n_components)
            X_transformed = self.pca.fit_transform(X)
            print(f"Explained variance ratio: {np.sum(self.pca.explained_variance_ratio):.4f}")
        else:
            X_transformed = X



        svm = SVM(learning_rate=0.001, lambda_param=0.01, n_iterations=10)
        svm.fit(X_transformed, y)
        self.models.append(svm)
        self.model_names.append("SVM")


        knn = KNN(k=3, distance_metric='euclidean', weights='distance')
        knn.fit(X_transformed, y)
        self.models.append(knn)
        self.model_names.append("KNN")


        self.specialized_4_9_classifier = LogisticRegression4vs9(learning_rate=0.1, n_iterations=500)
        mask_4_9 = np.isin(y, [4, 9])
        if np.sum(mask_4_9) > 0:
            self.specialized_4_9_classifier.fit(X_transformed[mask_4_9], y[mask_4_9])

            test_predictions = self.specialized_4_9_classifier.predict(X_transformed[mask_4_9])
            test_accuracy = accuracy_score(y[mask_4_9], test_predictions)
            print(f"   4vs9 LR training accuracy: {test_accuracy*100:.2f}%")

        self.specialized_5_8_classifier = LogisticRegression5vs8(learning_rate=0.1, n_iterations=500)
        mask_5_8 = np.isin(y, [5, 8])
        if np.sum(mask_5_8) > 0:
            self.specialized_5_8_classifier.fit(X_transformed[mask_5_8], y[mask_5_8])
            test_predictions = self.specialized_5_8_classifier.predict(X_transformed[mask_5_8])
            test_accuracy = accuracy_score(y[mask_5_8], test_predictions)
            print(f"   5vs8 LR training accuracy: {test_accuracy*100:.2f}%")

        return self

    def predict(self, X):
        if self.use_pca:
            X_transformed = self.pca.transform(X)
        else:
            X_transformed = X


        if self.voting == 'soft':
            all_probas = []
            for model in self.models:
                if hasattr(model, 'predict_proba'):
                    proba = model.predict_proba(X_transformed)
                else:
                    pred = model.predict(X_transformed)
                    proba = np.zeros((len(pred), 10))
                    proba[np.arange(len(pred)), pred.astype(int)] = 1
                all_probas.append(proba)
            avg_proba = np.mean(all_probas, axis=0)
            base_predictions = np.argmax(avg_proba, axis=1)
        else:

            pass


        final_predictions = base_predictions.copy()

        for i in range(len(X_transformed)):
            if base_predictions[i] in [4, 9] and self.specialized_4_9_classifier:
                final_predictions[i] = self.specialized_4_9_classifier.predict([X_transformed[i]])[0]
            elif base_predictions[i] in [5, 8] and self.specialized_5_8_classifier:
                final_predictions[i] = self.specialized_5_8_classifier.predict([X_transformed[i]])[0]

        return final_predictions

class EnhancedSVM_KNN_Ensemble:
    def __init__(self, use_pca=True, n_components=100, voting='soft'):
        self.use_pca = use_pca
        self.n_components = n_components
        self.voting = voting
        self.pca = None
        self.models = []
        self.model_names = []
        self.specialized_4_9_classifier = None
        self.specialized_5_8_classifier = None

    def fit(self, X, y):
        if self.use_pca:

            self.pca = PCA(self.n_components)
            X_transformed = self.pca.fit_transform(X)
            print(f"Explained variance ratio: {np.sum(self.pca.explained_variance_ratio):.4f}")
        else:
            X_transformed = X



        svm = SVM(learning_rate=0.001, lambda_param=0.01, n_iterations=10)
        svm.fit(X_transformed, y)
        self.models.append(svm)
        self.model_names.append("SVM")


        knn = KNN(k=3, distance_metric='euclidean', weights='distance')
        knn.fit(X_transformed, y)
        self.models.append(knn)
        self.model_names.append("KNN")


        self.specialized_4_9_classifier = LogisticRegression4vs9(learning_rate=0.1, n_iterations=500)
        mask_4_9 = np.isin(y, [4, 9])
        if np.sum(mask_4_9) > 0:
            self.specialized_4_9_classifier.fit(X_transformed[mask_4_9], y[mask_4_9])

            test_predictions = self.specialized_4_9_classifier.predict(X_transformed[mask_4_9])
            test_accuracy = accuracy_score(y[mask_4_9], test_predictions)
            print(f"   4vs9 LR training accuracy: {test_accuracy*100:.2f}%")

        self.specialized_5_8_classifier = LogisticRegression5vs8(learning_rate=0.1, n_iterations=500)
        mask_5_8 = np.isin(y, [5, 8])
        if np.sum(mask_5_8) > 0:
            self.specialized_5_8_classifier.fit(X_transformed[mask_5_8], y[mask_5_8])
            test_predictions = self.specialized_5_8_classifier.predict(X_transformed[mask_5_8])
            test_accuracy = accuracy_score(y[mask_5_8], test_predictions)
            print(f"   5vs8 LR training accuracy: {test_accuracy*100:.2f}%")



        return self

    def predict(self, X):
        if self.use_pca:
            X_transformed = self.pca.transform(X)
        else:
            X_transformed = X

        if self.voting == 'soft':
            all_probas = []
            for model in self.models:
                if hasattr(model, 'predict_proba'):
                    proba = model.predict_proba(X_transformed)
                else:
                    pred = model.predict(X_transformed)
                    proba = np.zeros((len(pred), 10))
                    proba[np.arange(len(pred)), pred.astype(int)] = 1
                all_probas.append(proba)
            avg_proba = np.mean(all_probas, axis=0)
            base_predictions = np.argmax(avg_proba, axis=1)
        else:

            all_predictions = []
            for model in self.models:
                pred = model.predict(X_transformed)
                all_predictions.append(pred)
            all_predictions = np.array(all_predictions)
            base_predictions = []
            for i in range(X.shape[0]):
                votes = all_predictions[:, i]
                base_predictions.append(Counter(votes).most_common(1)[0][0])
            base_predictions = np.array(base_predictions)


        final_predictions = base_predictions.copy()

        for i in range(len(X_transformed)):
            if base_predictions[i] in [4, 9] and self.specialized_4_9_classifier:
                final_predictions[i] = self.specialized_4_9_classifier.predict([X_transformed[i]])[0]
            elif base_predictions[i] in [5, 8] and self.specialized_5_8_classifier:
                final_predictions[i] = self.specialized_5_8_classifier.predict([X_transformed[i]])[0]

        return final_predictions

    def predict_proba(self, X):

        if self.use_pca:
            X_transformed = self.pca.transform(X)
        else:
            X_transformed = X

        all_probas = []
        for model in self.models:
            if hasattr(model, 'predict_proba'):
                proba = model.predict_proba(X_transformed)
            else:
                pred = model.predict(X_transformed)
                proba = np.zeros((len(pred), 10))
                proba[np.arange(len(pred)), pred.astype(int)] = 1
            all_probas.append(proba)

        return np.mean(all_probas, axis=0)

    def evaluate_individual_models(self, X, y):

        if self.use_pca:
            X_transformed = self.pca.transform(X)
        else:
            X_transformed = X


        from sklearn.metrics import accuracy_score

        for model, name in zip(self.models, self.model_names):
            pred = model.predict(X_transformed)
            acc = accuracy_score(y, pred)
            print(f"{name:25s}: {acc*100:.2f}%")

        if self.specialized_4_9_classifier:
            mask_4_9 = np.isin(y, [4, 9])
            if np.sum(mask_4_9) > 0:
                X_4_9 = X_transformed[mask_4_9]
                y_4_9 = y[mask_4_9]
                spec_pred_4_9 = self.specialized_4_9_classifier.predict(X_4_9)
                spec_acc_4_9 = accuracy_score(y_4_9, spec_pred_4_9)
                print(f"{'4vs9 Logistic Regression':25s}: {spec_acc_4_9*100:.2f}%")

        if self.specialized_5_8_classifier:
            mask_5_8 = np.isin(y, [5, 8])
            if np.sum(mask_5_8) > 0:
                X_5_8 = X_transformed[mask_5_8]
                y_5_8 = y[mask_5_8]
                spec_pred_5_8 = self.specialized_5_8_classifier.predict(X_5_8)
                spec_acc_5_8 = accuracy_score(y_5_8, spec_pred_5_8)
                print(f"{'5vs8 Logistic Regression':25s}: {spec_acc_5_8*100:.2f}%")


    def evaluate_specialized_classifiers(self, X, y):

        if self.use_pca:
            X_transformed = self.pca.transform(X)
        else:
            X_transformed = X

        if self.specialized_4_9_classifier:
            mask_4_9 = np.isin(y, [4, 9])
            if np.sum(mask_4_9) > 0:
                X_4_9 = X_transformed[mask_4_9]
                y_4_9 = y[mask_4_9]
                spec_pred_4_9 = self.specialized_4_9_classifier.predict(X_4_9)
                spec_acc_4_9 = accuracy_score(y_4_9, spec_pred_4_9)

                cm_4_9 = confusion_matrix(y_4_9, spec_pred_4_9, labels=[4, 9])
                print(f"4vs9 Logistic Regression Accuracy: {spec_acc_4_9*100:.2f}%")
                print("4vs9 Confusion Matrix:")
                print(f"  Actual 4s → Predicted 4: {cm_4_9[0,0]}")
                print(f"  Actual 4s → Predicted 9: {cm_4_9[0,1]}")
                print(f"  Actual 9s → Predicted 4: {cm_4_9[1,0]}")
                print(f"  Actual 9s → Predicted 9: {cm_4_9[1,1]}")


        if self.specialized_5_8_classifier:
            mask_5_8 = np.isin(y, [5, 8])
            if np.sum(mask_5_8) > 0:
                X_5_8 = X_transformed[mask_5_8]
                y_5_8 = y[mask_5_8]
                spec_pred_5_8 = self.specialized_5_8_classifier.predict(X_5_8)
                spec_acc_5_8 = accuracy_score(y_5_8, spec_pred_5_8)

                cm_5_8 = confusion_matrix(y_5_8, spec_pred_5_8, labels=[5, 8])
                print(f"5vs8 Logistic Regression Accuracy: {spec_acc_5_8*100:.2f}%")
                print("5vs8 Confusion Matrix:")
                print(f"  Actual 5s → Predicted 5: {cm_5_8[0,0]}")
                print(f"  Actual 5s → Predicted 8: {cm_5_8[0,1]}")
                print(f"  Actual 8s → Predicted 5: {cm_5_8[1,0]}")
                print(f"  Actual 8s → Predicted 8: {cm_5_8[1,1]}")

"""## **final model**"""

import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def read_data_multiclass(trainfile='MNIST_train.csv', validationfile='MNIST_validation.csv'):

    dftrain = pd.read_csv(trainfile)
    dfval = pd.read_csv(validationfile)

    featurecols = [col for col in dftrain.columns if col not in ['label', 'even']]
    targetcol = 'label'

    Xtrain = dftrain[featurecols]
    ytrain = dftrain[targetcol]

    Xval = dfval[featurecols]
    yval = dfval[targetcol]

    return (Xtrain, ytrain, Xval, yval)

Xtrain, ytrain, Xval, yval = read_data_multiclass()

Xtrain_np = Xtrain.values.astype(np.float32) / 255.0
Xval_np = Xval.values.astype(np.float32) / 255.0
ytrain_np = ytrain.values
yval_np = yval.values

from collections import Counter
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

class PCA:


    def __init__(self, n_components):
        self.n_components = n_components
        self.components = None
        self.mean = None
        self.explained_variance_ratio = None

    def fit(self, X):

        self.mean = np.mean(X, axis=0)
        X_centered = X - self.mean


        cov_matrix = np.cov(X_centered, rowvar=False)

        eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)


        sorted_indices = np.argsort(eigenvalues)[::-1]
        eigenvalues = eigenvalues[sorted_indices]
        eigenvectors = eigenvectors[:, sorted_indices]


        self.components = eigenvectors[:, :self.n_components]


        total_variance = np.sum(eigenvalues)
        self.explained_variance_ratio = eigenvalues[:self.n_components] / total_variance

        return self

    def transform(self, X):
        X_centered = X - self.mean
        return np.dot(X_centered, self.components)

    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)

class KNN:


    def __init__(self, k=5, distance_metric='euclidean', weights='uniform'):
        self.k = k
        self.distance_metric = distance_metric
        self.weights = weights
        self.X_train = None
        self.y_train = None

    def _calculate_distance(self, x1, x2):

        if self.distance_metric == 'euclidean':
            return np.sqrt(np.sum((x1 - x2) ** 2))
        elif self.distance_metric == 'manhattan':
            return np.sum(np.abs(x1 - x2))
        elif self.distance_metric == 'cosine':
            dot_product = np.dot(x1, x2)
            norm_x1 = np.linalg.norm(x1)
            norm_x2 = np.linalg.norm(x2)
            return 1 - (dot_product / (norm_x1 * norm_x2))
        else:
            raise ValueError("Unsupported distance metric")

    def fit(self, X, y):

        self.X_train = X
        self.y_train = y
        return self

    def predict_single(self, x):

        distances = []


        for i, x_train in enumerate(self.X_train):
            dist = self._calculate_distance(x, x_train)
            distances.append((dist, self.y_train[i]))


        distances.sort(key=lambda x: x[0])
        k_nearest = distances[:self.k]


        labels = [label for _, label in k_nearest]
        dists = [dist for dist, _ in k_nearest]


        if self.weights == 'distance':

            weights = [1 / (d + 1e-8) for d in dists]
            weight_dict = {}
            for label, weight in zip(labels, weights):
                if label in weight_dict:
                    weight_dict[label] += weight
                else:
                    weight_dict[label] = weight

            return max(weight_dict.items(), key=lambda x: x[1])[0]

        else:

            return Counter(labels).most_common(1)[0][0]

    def predict(self, X):

        return np.array([self.predict_single(x) for x in X])

    def predict_proba(self, X):

        probabilities = []

        for x in X:
            distances = []


            for i, x_train in enumerate(self.X_train):
                dist = self._calculate_distance(x, x_train)
                distances.append((dist, self.y_train[i]))


            distances.sort(key=lambda x: x[0])
            k_nearest = distances[:self.k]


            labels = [label for _, label in k_nearest]


            label_counts = Counter(labels)
            prob = np.zeros(10)

            for label, count in label_counts.items():
                prob[label] = count / self.k

            probabilities.append(prob)

        return np.array(probabilities)

import numpy as np
from collections import Counter

class SVM:


    def __init__(self, learning_rate=0.001, lambda_param=0.01, n_iterations=1000):
        self.learning_rate = learning_rate
        self.lambda_param = lambda_param
        self.n_iterations = n_iterations
        self.classifiers = []
        self.classes = None

    def _train_binary(self, X, y):

        n_samples, n_features = X.shape
        w = np.zeros(n_features)
        b = 0


        y_ = np.where(y <= 0, -1, 1)

        for _ in range(self.n_iterations):
            for idx, x_i in enumerate(X):
                condition = y_[idx] * (np.dot(x_i, w) - b) >= 1

                if condition:
                    w -= self.learning_rate * (2 * self.lambda_param * w)
                else:
                    w -= self.learning_rate * (2 * self.lambda_param * w - np.dot(x_i, y_[idx]))
                    b -= self.learning_rate * y_[idx]

        return w, b

    def fit(self, X, y):
        self.classes = np.unique(y)


        for c in self.classes:

            y_binary = np.where(y == c, 1, -1)
            w, b = self._train_binary(X, y_binary)
            self.classifiers.append((w, b))

        return self

    def _decision_function(self, X):
        scores = []
        for w, b in self.classifiers:
            score = np.dot(X, w) - b
            scores.append(score)
        return np.array(scores).T

    def predict(self, X):
        scores = self._decision_function(X)
        return self.classes[np.argmax(scores, axis=1)]

    def predict_proba(self, X):

        scores = self._decision_function(X)

        exp_scores = np.exp(scores - np.max(scores, axis=1, keepdims=True))
        probas = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)
        return probas

class LogisticRegression4vs9:
    def __init__(self, learning_rate=0.01, n_iterations=1000):
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.weights = None
        self.bias = None

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-np.clip(z, -250, 250)))

    def fit(self, X, y):

        y_binary = (y == 9).astype(int)

        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0


        for _ in range(self.n_iterations):
            linear_model = np.dot(X, self.weights) + self.bias
            predictions = self.sigmoid(linear_model)

            dw = (1 / n_samples) * np.dot(X.T, (predictions - y_binary))
            db = (1 / n_samples) * np.sum(predictions - y_binary)

            self.weights -= self.learning_rate * dw
            self.bias -= self.learning_rate * db

    def predict_proba(self, X):
        linear_model = np.dot(X, self.weights) + self.bias
        return self.sigmoid(linear_model)

    def predict(self, X):
        proba = self.predict_proba(X)
        return np.where(proba > 0.5, 9, 4)

class Final_Model:
    def __init__(self, use_pca=True, n_components=100, voting='soft'):
        self.use_pca = use_pca
        self.n_components = n_components
        self.voting = voting
        self.pca = None
        self.models = []
        self.model_names = []
        self.specialized_4_9_classifier = None
        self.specialized_5_8_classifier = None

    def fit(self, X, y):
        if self.use_pca:

            self.pca = PCA(self.n_components)
            X_transformed = self.pca.fit_transform(X)
            print(f"Explained variance ratio: {np.sum(self.pca.explained_variance_ratio):.4f}")
        else:
            X_transformed = X



        svm = SVM(learning_rate=0.001, lambda_param=0.01, n_iterations=10)
        svm.fit(X_transformed, y)
        self.models.append(svm)
        self.model_names.append("SVM")


        knn = KNN(k=5, distance_metric='euclidean', weights='distance')
        knn.fit(X_transformed, y)
        self.models.append(knn)
        self.model_names.append("KNN")

        self.specialized_4_9_classifier = LogisticRegression4vs9(learning_rate=0.1, n_iterations=500)
        mask_4_9 = np.isin(y, [4, 9])
        if np.sum(mask_4_9) > 0:
            self.specialized_4_9_classifier.fit(X_transformed[mask_4_9], y[mask_4_9])

            test_predictions = self.specialized_4_9_classifier.predict(X_transformed[mask_4_9])
            test_accuracy = accuracy_score(y[mask_4_9], test_predictions)
            print(f"   4vs9 LR training accuracy: {test_accuracy*100:.2f}%")




        return self

    def predict(self, X):
        if self.use_pca:
            X_transformed = self.pca.transform(X)
        else:
            X_transformed = X

        if self.voting == 'soft':
            all_probas = []
            for model in self.models:
                if hasattr(model, 'predict_proba'):
                    proba = model.predict_proba(X_transformed)
                else:
                    pred = model.predict(X_transformed)
                    proba = np.zeros((len(pred), 10))
                    proba[np.arange(len(pred)), pred.astype(int)] = 1
                all_probas.append(proba)
            avg_proba = np.mean(all_probas, axis=0)
            base_predictions = np.argmax(avg_proba, axis=1)
        else:

            all_predictions = []
            for model in self.models:
                pred = model.predict(X_transformed)
                all_predictions.append(pred)
            all_predictions = np.array(all_predictions)
            base_predictions = []
            for i in range(X.shape[0]):
                votes = all_predictions[:, i]
                base_predictions.append(Counter(votes).most_common(1)[0][0])
            base_predictions = np.array(base_predictions)

        final_predictions = base_predictions.copy()

        for i in range(len(X_transformed)):
            if base_predictions[i] in [4, 9] and self.specialized_4_9_classifier:
                final_predictions[i] = self.specialized_4_9_classifier.predict([X_transformed[i]])[0]

        return final_predictions

    def predict_proba(self, X):

        if self.use_pca:
            X_transformed = self.pca.transform(X)
        else:
            X_transformed = X

        all_probas = []
        for model in self.models:
            if hasattr(model, 'predict_proba'):
                proba = model.predict_proba(X_transformed)
            else:
                pred = model.predict(X_transformed)
                proba = np.zeros((len(pred), 10))
                proba[np.arange(len(pred)), pred.astype(int)] = 1
            all_probas.append(proba)

        return np.mean(all_probas, axis=0)

    def evaluate_individual_models(self, X, y):

        if self.use_pca:
            X_transformed = self.pca.transform(X)
        else:
            X_transformed = X



        from sklearn.metrics import accuracy_score

        for model, name in zip(self.models, self.model_names):
            pred = model.predict(X_transformed)
            acc = accuracy_score(y, pred)
            print(f"{name:25s}: {acc*100:.2f}%")


        if self.specialized_4_9_classifier:
            mask_4_9 = np.isin(y, [4, 9])
            if np.sum(mask_4_9) > 0:
                X_4_9 = X_transformed[mask_4_9]
                y_4_9 = y[mask_4_9]
                spec_pred_4_9 = self.specialized_4_9_classifier.predict(X_4_9)
                spec_acc_4_9 = accuracy_score(y_4_9, spec_pred_4_9)
                print(f"{'4vs9 Logistic Regression':25s}: {spec_acc_4_9*100:.2f}%")