# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ki3e6kn5BnUZgVlWPT6fFf_PJv-IW-sx
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

dftrain = pd.read_csv('/content/MNIST_train.csv')
dfval = pd.read_csv('/content/MNIST_validation.csv')

dftrain.drop('even',axis=1,inplace=True)
dfval.drop('even',axis=1,inplace=True)

import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def read_data_multiclass(trainfile='MNIST_train.csv', validationfile='MNIST_validation.csv'):

    dftrain = pd.read_csv(trainfile)
    dfval = pd.read_csv(validationfile)

    featurecols = [col for col in dftrain.columns if col not in ['label', 'even']]
    targetcol = 'label'

    Xtrain = dftrain[featurecols]
    ytrain = dftrain[targetcol]

    Xval = dfval[featurecols]
    yval = dfval[targetcol]

    return (Xtrain, ytrain, Xval, yval)

Xtrain, ytrain, Xval, yval = read_data_multiclass('MNIST_train.csv','MNIST_validation.csv')

print(len(Xval))

"""PCA"""

from collections import Counter
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

class PCA:


    def __init__(self, n_components):
        self.n_components = n_components
        self.components = None
        self.mean = None
        self.explained_variance_ratio = None

    def fit(self, X):

        self.mean = np.mean(X, axis=0)
        X_centered = X - self.mean

        cov_matrix = np.cov(X_centered, rowvar=False)

        eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)


        sorted_indices = np.argsort(eigenvalues)[::-1]
        eigenvalues = eigenvalues[sorted_indices]
        eigenvectors = eigenvectors[:, sorted_indices]


        self.components = eigenvectors[:, :self.n_components]


        total_variance = np.sum(eigenvalues)
        self.explained_variance_ratio = eigenvalues[:self.n_components] / total_variance

        return self

    def transform(self, X):
        X_centered = X - self.mean
        return np.dot(X_centered, self.components)

    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)

Xtrain, ytrain, Xval, yval = read_data_multiclass()


Xtrain_np = Xtrain.values.astype(np.float32) / 255.0
Xval_np = Xval.values.astype(np.float32) / 255.0
ytrain_np = ytrain.values
yval_np = yval.values

"""KNN"""

class KNN:


    def __init__(self, k=5, distance_metric='euclidean', weights='uniform'):
        self.k = k
        self.distance_metric = distance_metric
        self.weights = weights
        self.X_train = None
        self.y_train = None

    def _calculate_distance(self, x1, x2):

        if self.distance_metric == 'euclidean':
            return np.sqrt(np.sum((x1 - x2) ** 2))
        elif self.distance_metric == 'manhattan':
            return np.sum(np.abs(x1 - x2))
        elif self.distance_metric == 'cosine':
            dot_product = np.dot(x1, x2)
            norm_x1 = np.linalg.norm(x1)
            norm_x2 = np.linalg.norm(x2)
            return 1 - (dot_product / (norm_x1 * norm_x2))
        else:
            raise ValueError("Unsupported distance metric")

    def fit(self, X, y):

        self.X_train = X
        self.y_train = y
        return self

    def predict_single(self, x):

        distances = []


        for i, x_train in enumerate(self.X_train):
            dist = self._calculate_distance(x, x_train)
            distances.append((dist, self.y_train[i]))


        distances.sort(key=lambda x: x[0])
        k_nearest = distances[:self.k]


        labels = [label for _, label in k_nearest]
        dists = [dist for dist, _ in k_nearest]


        if self.weights == 'distance':

            weights = [1 / (d + 1e-8) for d in dists]
            weight_dict = {}
            for label, weight in zip(labels, weights):
                if label in weight_dict:
                    weight_dict[label] += weight
                else:
                    weight_dict[label] = weight


            return max(weight_dict.items(), key=lambda x: x[1])[0]

        else:

            return Counter(labels).most_common(1)[0][0]

    def predict(self, X):

        return np.array([self.predict_single(x) for x in X])

    def predict_proba(self, X):

        probabilities = []

        for x in X:
            distances = []


            for i, x_train in enumerate(self.X_train):
                dist = self._calculate_distance(x, x_train)
                distances.append((dist, self.y_train[i]))


            distances.sort(key=lambda x: x[0])
            k_nearest = distances[:self.k]


            labels = [label for _, label in k_nearest]


            label_counts = Counter(labels)
            prob = np.zeros(10)

            for label, count in label_counts.items():
                prob[label] = count / self.k

            probabilities.append(prob)

        return np.array(probabilities)

"""SVM"""

import numpy as np
from collections import Counter

class SVM:


    def __init__(self, learning_rate=0.001, lambda_param=0.01, n_iterations=1000):
        self.learning_rate = learning_rate
        self.lambda_param = lambda_param
        self.n_iterations = n_iterations
        self.classifiers = []
        self.classes = None

    def _train_binary(self, X, y):

        n_samples, n_features = X.shape
        w = np.zeros(n_features)
        b = 0


        y_ = np.where(y <= 0, -1, 1)

        for _ in range(self.n_iterations):
            for idx, x_i in enumerate(X):
                condition = y_[idx] * (np.dot(x_i, w) - b) >= 1

                if condition:
                    w -= self.learning_rate * (2 * self.lambda_param * w)
                else:
                    w -= self.learning_rate * (2 * self.lambda_param * w - np.dot(x_i, y_[idx]))
                    b -= self.learning_rate * y_[idx]

        return w, b

    def fit(self, X, y):
        self.classes = np.unique(y)


        for c in self.classes:

            y_binary = np.where(y == c, 1, -1)
            w, b = self._train_binary(X, y_binary)
            self.classifiers.append((w, b))

        return self

    def _decision_function(self, X):

        scores = []
        for w, b in self.classifiers:
            score = np.dot(X, w) - b
            scores.append(score)
        return np.array(scores).T

    def predict(self, X):
        scores = self._decision_function(X)
        return self.classes[np.argmax(scores, axis=1)]

    def predict_proba(self, X):

        scores = self._decision_function(X)

        exp_scores = np.exp(scores - np.max(scores, axis=1, keepdims=True))
        probas = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)
        return probas

class LogisticRegression4vs9:
    def __init__(self, learning_rate=0.01, n_iterations=1000):
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.weights = None
        self.bias = None

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-np.clip(z, -250, 250)))

    def fit(self, X, y):

        y_binary = (y == 9).astype(int)

        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0


        for _ in range(self.n_iterations):
            linear_model = np.dot(X, self.weights) + self.bias
            predictions = self.sigmoid(linear_model)


            dw = (1 / n_samples) * np.dot(X.T, (predictions - y_binary))
            db = (1 / n_samples) * np.sum(predictions - y_binary)


            self.weights -= self.learning_rate * dw
            self.bias -= self.learning_rate * db

    def predict_proba(self, X):
        linear_model = np.dot(X, self.weights) + self.bias
        return self.sigmoid(linear_model)

    def predict(self, X):
        proba = self.predict_proba(X)
        return np.where(proba > 0.5, 9, 4)

class EnhancedSVM_KNN_Ensemble:
    def __init__(self, use_pca=True, n_components=100, voting='soft'):
        self.use_pca = use_pca
        self.n_components = n_components
        self.voting = voting
        self.pca = None
        self.models = []
        self.model_names = []
        self.specialized_4_9_classifier = None
        self.specialized_5_8_classifier = None

    def fit(self, X, y):
        if self.use_pca:

            self.pca = PCA(self.n_components)
            X_transformed = self.pca.fit_transform(X)

        else:
            X_transformed = X


        svm = SVM(learning_rate=0.001, lambda_param=0.01, n_iterations=100)
        svm.fit(X_transformed, y)
        self.models.append(svm)
        self.model_names.append("SVM")


        knn = KNN(k=5, distance_metric='euclidean', weights='distance')
        knn.fit(X_transformed, y)
        self.models.append(knn)
        self.model_names.append("KNN")


        self.specialized_4_9_classifier = LogisticRegression4vs9(learning_rate=0.1, n_iterations=500)
        mask_4_9 = np.isin(y, [4, 9])
        if np.sum(mask_4_9) > 0:
            self.specialized_4_9_classifier.fit(X_transformed[mask_4_9], y[mask_4_9])

            test_predictions = self.specialized_4_9_classifier.predict(X_transformed[mask_4_9])
            test_accuracy = accuracy_score(y[mask_4_9], test_predictions)




        return self

    def predict(self, X):
        if self.use_pca:
            X_transformed = self.pca.transform(X)
        else:
            X_transformed = X


        if self.voting == 'soft':
            all_probas = []
            for model in self.models:
                if hasattr(model, 'predict_proba'):
                    proba = model.predict_proba(X_transformed)
                else:
                    pred = model.predict(X_transformed)
                    proba = np.zeros((len(pred), 10))
                    proba[np.arange(len(pred)), pred.astype(int)] = 1
                all_probas.append(proba)
            avg_proba = np.mean(all_probas, axis=0)
            base_predictions = np.argmax(avg_proba, axis=1)
        else:

            all_predictions = []
            for model in self.models:
                pred = model.predict(X_transformed)
                all_predictions.append(pred)
            all_predictions = np.array(all_predictions)
            base_predictions = []
            for i in range(X.shape[0]):
                votes = all_predictions[:, i]
                base_predictions.append(Counter(votes).most_common(1)[0][0])
            base_predictions = np.array(base_predictions)


        final_predictions = base_predictions.copy()

        for i in range(len(X_transformed)):
            if base_predictions[i] in [4, 9] and self.specialized_4_9_classifier:
                final_predictions[i] = self.specialized_4_9_classifier.predict([X_transformed[i]])[0]

        return final_predictions

    def predict_proba(self, X):

        if self.use_pca:
            X_transformed = self.pca.transform(X)
        else:
            X_transformed = X

        all_probas = []
        for model in self.models:
            if hasattr(model, 'predict_proba'):
                proba = model.predict_proba(X_transformed)
            else:
                pred = model.predict(X_transformed)
                proba = np.zeros((len(pred), 10))
                proba[np.arange(len(pred)), pred.astype(int)] = 1
            all_probas.append(proba)

        return np.mean(all_probas, axis=0)

    def evaluate_individual_models(self, X, y):

        if self.use_pca:
            X_transformed = self.pca.transform(X)
        else:
            X_transformed = X



        from sklearn.metrics import accuracy_score

        for model, name in zip(self.models, self.model_names):
            pred = model.predict(X_transformed)
            acc = accuracy_score(y, pred)
            print(f"{name:25s}: {acc*100:.2f}%")


        if self.specialized_4_9_classifier:
            mask_4_9 = np.isin(y, [4, 9])
            if np.sum(mask_4_9) > 0:
                X_4_9 = X_transformed[mask_4_9]
                y_4_9 = y[mask_4_9]
                spec_pred_4_9 = self.specialized_4_9_classifier.predict(X_4_9)
                spec_acc_4_9 = accuracy_score(y_4_9, spec_pred_4_9)





    def evaluate_specialized_classifiers(self, X, y):

        if self.use_pca:
            X_transformed = self.pca.transform(X)
        else:
            X_transformed = X



        if self.specialized_4_9_classifier:
            mask_4_9 = np.isin(y, [4, 9])
            if np.sum(mask_4_9) > 0:
                X_4_9 = X_transformed[mask_4_9]
                y_4_9 = y[mask_4_9]
                spec_pred_4_9 = self.specialized_4_9_classifier.predict(X_4_9)
                spec_acc_4_9 = accuracy_score(y_4_9, spec_pred_4_9)

                cm_4_9 = confusion_matrix(y_4_9, spec_pred_4_9, labels=[4, 9])

from sklearn.metrics import f1_score
ensemble = EnhancedSVM_KNN_Ensemble(use_pca=True, n_components=50, voting='soft')
ensemble.fit(Xtrain_np, ytrain_np)



predictions_soft = ensemble.predict(Xval_np)
accuracy_soft = accuracy_score(yval_np, predictions_soft)
print(f"\nFINAL ENSEMBLE MODEL  ACCURACY: {accuracy_soft*100:.2f}%")

print("\nClassification Report:")
print(classification_report(yval_np, predictions_soft))
print(f"\nFINAL ENSEMBLE MODEL F1-SCORE:{f1_score(yval_np, predictions_soft, average='weighted')}")

